Fixes #490 - Add support for Namecheap
polymind-inc/acmebot pull request #501
Opened 2022-07-18 20:36 UTC by eloekset

An implemenation for [Namecheap](https://www.namecheap.com/).

I've deployed and used it for three of my own domains now and it works fine.

Since I can't send PRs for the wiki, this is the documentation that should be added about configuration of the Namecheap provider:

## Namecheap

### App settings

- `Acmebot:Namecheap:ApiKeyUser`
  - Your namecheap username (not an email address)
- `Acmebot:Namecheap:ApiKeyPassword`
  - API Key namecheap on you Profile -> Tools -> API Access page
### Example API Token configuration

Navigate to https://ap.www.namecheap.com/settings/tools/apiaccess/

![image](https://user-images.githubusercontent.com/791721/179612528-2acc90a8-ded9-4b00-a1c8-79bc89bf9289.png)

Client IP addresses must be whitelisted in your Namecheap account to be able to call the API. For Azure Function apps, this is a bit tricky, because you don't know which IP address the function app uses until it has tried and got rejected.

To find the IP address, you'll have to look at the Application Insights **Performance** view and look for logs on **GetZones**. There you should find an entry for **api.namecheap.com GET /xml.response** and the **Path** contains the **ClientIp=nn.nnn.nn.nnn** parameter showing the IP address that was used.

![image](https://user-images.githubusercontent.com/791721/179612452-12623f0c-69c1-4723-8c08-e3efbbb04f12.png)

You have to go to your Namecheap profile page and whitelist this IP address.

![image](https://user-images.githubusercontent.com/791721/179612591-5ba09dbc-22ea-42fc-acc7-d6e9dee45a31.png)

But there's no guarantee that the function app uses the same IP address when it renews the certificates some months later.

2022-07-18 20:37 UTC, eloekset commented
Link to Issue #490

2022-12-18 07:48 UTC, shibayan requested changes

2022-12-18 07:48 UTC, shibayan commented on KeyVault.Acmebot/Startup.cs
> +            dnsProviders.TryAdd(options.Namecheap, o => new NamecheapProvider(o, HttpClientFactory.Create(), HttpClientFactory.Create()));
HttpClient should be instantiated inside the Provider. Implementation uniformity with other Providers is important.

2022-12-18 07:48 UTC, shibayan commented on KeyVault.Acmebot/Providers/NamecheapProvider.cs
> +    public NamecheapProvider(NamecheapOptions options, HttpClient namecheapHttpClient, HttpClient ipfyOrgHttpClient)
As with other Providers, the implementation of the IDnsProvider interface should be separated from the DNS API implementation class.

This is necessary for implementation consistency as well as to be resilient to future API changes.

2022-12-18 07:48 UTC, shibayan commented on KeyVault.Acmebot/Providers/NamecheapProvider.cs
> +        return ipFyResponse.Ip;
Azure Functions do not always match the Outbound IP between each request. Therefore, there is a possibility of unintended behavior when the obtained Outbound IP changes.

2026-05-20 06:51 UTC, shibayan commented
Closing this stale PR as part of backlog cleanup. It has been open since 2022, has unresolved requested changes, and has not been updated to match the current codebase. If you still want to pursue Namecheap support, please open a new PR rebased on the current master branch with the requested changes addressed.

2026-05-20 06:51 UTC, closed without merging