Add OVH Provider
polymind-inc/acmebot pull request #650
Opened 2023-12-12 08:40 UTC by bhubert

I added OVH which is a cloud / DNS / domain provider really popular in France and at least Europe.

The code is complex because their api is complicated to call with a signature to generate based on the content of the call that needs to be added in header on each requests

2023-12-17 15:27 UTC, bhubert commented
hi @shibayan ! do you think you will accept this PR or is OVH to small in your opinion to make it a great addition to your project ?

2023-12-18 07:28 UTC, shibayan requested changes
Overall, the structure and format of the code should be consistent with other provider implementations. Consistency with other provider implementations must be maintained.

e.g. https://github.com/shibayan/keyvault-acmebot/blob/master/KeyVault.Acmebot/Providers/GoDaddyProvider.cs

2023-12-18 07:28 UTC, shibayan commented on KeyVault.Acmebot/Options/OVHOptions.cs
> +public class OVHOptions
```suggestion
public class OvhOptions
```

2023-12-18 07:28 UTC, shibayan commented on KeyVault.Acmebot/Providers/OVHProvider.cs
> +public class OVHDnsProvider : IDnsProvider
```suggestion
public class OvhProvider : IDnsProvider
```

2023-12-18 08:29 UTC, bhubert commented on KeyVault.Acmebot/Options/OVHOptions.cs
> +public class OVHOptions
done

2023-12-18 08:29 UTC, bhubert commented on KeyVault.Acmebot/Providers/OVHProvider.cs
> +public class OVHDnsProvider : IDnsProvider
done

2023-12-18 08:30 UTC, bhubert commented
> Overall, the structure and format of the code should be consistent with other provider implementations. Consistency with other provider implementations must be maintained.
> 
> e.g. https://github.com/shibayan/keyvault-acmebot/blob/master/KeyVault.Acmebot/Providers/GoDaddyProvider.cs

I reordered and rewrote some part of the code to make it looks like GoDaddy provider as much as possible. You were right it's much better like this, thanks !

2024-03-24 14:10 UTC, bhubert commented
> > Overall, the structure and format of the code should be consistent with other provider implementations. Consistency with other provider implementations must be maintained.
> > e.g. https://github.com/shibayan/keyvault-acmebot/blob/master/KeyVault.Acmebot/Providers/GoDaddyProvider.cs
> 
> I reordered and rewrote some part of the code to make it looks like GoDaddy provider as much as possible. You were right it's much better like this, thanks !

@shibayan it's been a while and i forgot about this PR, could you check if the last version was ok ? thanks !

2026-02-20 14:04 UTC, CisorKnight commented
Any chance it could be merged in the main?
I would really like to use keyvault-acmebot with ovh as a dns provider

2026-03-18 15:39 UTC, shibayan approved these changes

2026-03-18 15:46 UTC, shibayan commented
@copilot open a new pull request to apply changes based on the comments in [this thread](https://github.com/polymind-inc/acmebot/pull/650#pullrequestreview-3968849125)

2026-05-18 08:01 UTC, shibayan commented
Closed by #1065

2026-05-18 08:01 UTC, closed without merging